In [1]:
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
import os
from sklearn.metrics import r2_score
from sklearn import svm

In [51]:
bf_arr = []
pi_arr = []

opt = cv2.IMREAD_GRAYSCALE

#path = "/home/maiki/Downloads/ht29/"
path = "/home/maiki/Downloads/pancreas/"
#path = "/home/maiki/Downloads/both/"
for img in os.listdir(path+"imgs"):
    print(img+"...")
    bf = cv2.resize(cv2.imread(path+"/imgs/"+img, opt), (256,256))
    bf = np.float32((255-bf.reshape((-1,1))))
    bf = bf/max(bf)
    bf_arr.append(bf)

for img in os.listdir(path+"pi"):
    print(img+"...")
    pi = cv2.resize(cv2.imread(path+"/pi/"+img, opt), (256,256))
    pi = np.float32((pi.reshape((-1,1))))
    pi = pi/max(pi)
    pi_arr.append(pi)

e11_p.jpg...
d9_p.jpg...
d10_p.jpg...
e8_p.jpg...
g11_p.jpg...
g9_p.jpg...
g8_p.jpg...
c9_p.jpg...
e10_p.jpg...
h10_p.jpg...
g10_p.jpg...
f9_p.jpg...
d8_p.jpg...
f8_p.jpg...
h9_p.jpg...
a10_p.jpg...
e9_p.jpg...
f11_p.jpg...
a8_p.jpg...
b11_p.jpg...
a9_p.jpg...
c8_p.jpg...
c11_p.jpg...
d11_p.jpg...
f10_p.jpg...
b8_p.jpg...
h11_p.jpg...
b9_p.jpg...
b10_p.jpg...
c10_p.jpg...
h8_p.jpg...
e11_p.jpg...
d9_p.jpg...
d10_p.jpg...
e8_p.jpg...
g11_p.jpg...
g9_p.jpg...
g8_p.jpg...
c9_p.jpg...
e10_p.jpg...
h10_p.jpg...
g10_p.jpg...
f9_p.jpg...
d8_p.jpg...
f8_p.jpg...
h9_p.jpg...
a10_p.jpg...
e9_p.jpg...
f11_p.jpg...
a8_p.jpg...
b11_p.jpg...
a9_p.jpg...
c8_p.jpg...
c11_p.jpg...
d11_p.jpg...
f10_p.jpg...
b8_p.jpg...
h11_p.jpg...
b9_p.jpg...
b10_p.jpg...
c10_p.jpg...
h8_p.jpg...


In [54]:
for i in range(len(pi_arr)):
  pi_arr[i]=pi_arr[i][:,0]
  

In [4]:
def imshow(img):
    cv2.namedWindow("out", cv2.WINDOW_NORMAL)
    cv2.imshow("out",(img).astype(np.uint8))
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [11]:
imshow(pi.reshape((256,256))*255)

In [66]:
np.unique(pi_m*127, return_counts=True)

(array([  0, 127, 254], dtype=uint8), array([57582,  4386,  3568]))

In [55]:
x1_tr, x1_tst, y1_tr, y1_tst = train_test_split(bf_arr, pi_arr, test_size=0.3, random_state=23)

In [56]:
x1_tr = np.concatenate((x1_tr[:]))
y1_tr = np.concatenate((y1_tr[:]))
x1_tst = np.concatenate((x1_tst[:]))
y1_tst = np.concatenate((y1_tst[:]))

In [57]:
print(x1_tr.shape)
print(y1_tr.shape)
print(x1_tst.shape)
print(y1_tst.shape)

(1376256, 1)
(1376256,)
(655360, 1)
(655360,)


In [58]:
dt = DecisionTreeRegressor()

dt.fit(x1_tr, y1_tr)

y_pred = dt.predict(x1_tst)

In [8]:
lr = LinearRegression()
lr.fit(x1_tr, y1_tr)

y_pred = lr.predict(x1_tst)

In [10]:
imshow(y_pred[:256*256].reshape(256,256)*255)

In [59]:
print(r2_score(y1_tst, y_pred))

0.23724203192380977


In [60]:
#th = []
#for thresh in np.arange(0.01,0.99,0.01):
sim = []
for i in range(int(len(y1_tst)/(256*256))):
    lo = i*256*256
    hi = (i+1)*256*256
    pred = (y_pred[lo:hi]).reshape(256,256)*255
    tst = (y1_tst[lo:hi]).reshape(256,256)*255
    try:
        sim.append(cv2.matchTemplate(pred.astype(np.uint8), tst.astype(np.uint8), method = cv2.TM_CCOEFF_NORMED)[0][0])
    except:
        sim.append(0)
    imshow(np.concatenate((tst, pred),axis = 1))
    print(sim[len(sim)-1])


print("average: "+str(np.average(sim)))
#   th.append(np.average(sim))

# print(np.argmax(th))

0.5702821
0.6057386
0.48877698
0.5266863
0.7774107
0.69927067
0.6017612
0.5175689
0.394986
0.6876749
average: 0.5870157


In [23]:
img_t = y1_tst[:256*256].reshape(256,256)*255
img_p = y_pred[:256*256].reshape(256,256)*255

In [24]:
imshow(np.concatenate((img_t,img_p), axis = 1))

In [26]:
cv2.matchTemplate(img_t.astype(np.uint8), img_p.astype(np.uint8), method=cv2.TM_CCOEFF_NORMED)

array([[0.94965047]], dtype=float32)

In [41]:
pred = (f4_pred).reshape(256,256)*255
cv2.imwrite(path+"f4_pred.jpg", pred)

True

In [37]:
f4_pred = dt.predict(bf_arr[55])

In [ ]:
i = 0
for img in os.listdir(path+"pi"):
    print(img+"...")
    y_pred = dt.predict(bf_arr[i]).reshape(256,256)*255
    cv2.imwrite(path+'/results_dt_regressor/'+img, y_pred)
    i+=1

# One image

In [18]:
bf = cv2.imread("/home/maiki/Downloads/bf.JPG", cv2.IMREAD_GRAYSCALE)
pi_m_3 = cv2.imread("/home/maiki/Downloads/pi_m_3.JPG", cv2.IMREAD_GRAYSCALE)


bf_neg = 255-bf

pi_m_3_fixed = extrapolate_kmeans(pi_m_3)

trainingData = np.float32(bf_neg.reshape((-1,1)))
# labels = (pi_m_3_fixed/255).reshape((-1,1))


mask1 = pi_m_3_fixed == 1
mask2 = pi_m_3_fixed == 2



In [27]:
labels1 = (mask1).reshape((-1,1))
labels2 = (mask2).reshape((-1,1))

trainingData = trainingData/max(trainingData)


x1_tr, x1_tst, y1_tr, y1_tst = train_test_split(trainingData, labels1, test_size=0.2, random_state=23)
x2_tr, x2_tst, y2_tr, y2_tst = train_test_split(trainingData, labels2, test_size=0.2, random_state=23)


In [21]:
np.unique(mask1*255)

array([  0, 255])

In [29]:
y2_tr = y2_tr[:,0]
y2_tst = y2_tst[:,0]

print(x2_tr.shape)
print(y2_tr.shape)
print(x2_tst.shape)
print(y2_tst.shape)


(3355443, 1)
(3355443,)
(838861, 1)
(838861,)


In [7]:
dt = DecisionTreeRegressor()

dt.fit(x_tr, y_tr)

y_pred = dt.predict(x_tst)

In [16]:
from sklearn.metrics import r2_score
print(r2_score(y_tst, y_pred))

0.013428493422678791
0.0016986248010660487
0.041214376145539904
0.9045785579856036


In [30]:
lr = LogisticRegression(max_iter=1000)

lr.fit(x1_tr,y1_tr)
y1_pred = lr.predict_proba(x1_tst)[::,1]
print(quality_metrics(y1_tst, y1_pred ))

lr.fit(x2_tr,y2_tr)
y2_pred = lr.predict_proba(x2_tst)[::,1]
print(quality_metrics(y2_tst, y2_pred ))

(0.9117480753095828, 0.9265897449041021, 0.0, 0.9973413810447654)
(0.9972711927099481, 0.9903595470524914, 0.9388594632768361, 0.9940886271271162)
